[package]
name = "bili_sync"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = { workspace = true }
publish = { workspace = true }
readme = "../../README.md"
build = "build.rs"

[dependencies]
anyhow = { workspace = true }
arc-swap = { workspace = true }
async-stream = { workspace = true }
base64 = { workspace = true }
# atty = "0.2.14" # 已移除：未使用
axum = { workspace = true }
bili_sync_entity = { workspace = true }
bili_sync_migration = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
cookie = { workspace = true }
cow-utils = { workspace = true }
dashmap = { workspace = true }
dirs = { workspace = true }
enum_dispatch = { workspace = true }
float-ord = { workspace = true }
futures = { workspace = true }
# glob = { workspace = true } # 已移除：未使用
handlebars = { workspace = true }
hex = { workspace = true }
html-escape = { workspace = true }
# indicatif = "0.17.11" # 已移除：未使用
lazy_static = "1.5.0"
leaky-bucket = { workspace = true }
md5 = { workspace = true }
memchr = { workspace = true }
mime_guess = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
prost = { workspace = true }
quick-xml = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
rsa = { workspace = true }
rust-embed = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
strum = { workspace = true }
sysinfo = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tokio-tungstenite = { workspace = true }
# toml = { workspace = true } # 已移除：配置已迁移到数据库
# toml_edit = { workspace = true } # 已移除：配置已迁移到数据库
# tower = { workspace = true } # 已移除：未使用
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
uuid = { workspace = true }
flate2 = { workspace = true }
byteorder = { workspace = true }

[dev-dependencies]
arc-swap.workspace = true
assert_matches = { workspace = true }

[build-dependencies]
built = { workspace = true }

[package.metadata.release]
release = true

[[bin]]
name = "bili-sync-rs"
path = "src/main.rs"
