//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::collection::Entity as Collection;
pub use super::config_item::Entity as ConfigItem;
pub use super::favorite::Entity as Favorite;
pub use super::live_monitor::Entity as LiveMonitor;
pub use super::live_record::Entity as LiveRecord;
pub use super::page::Entity as Page;
pub use super::submission::Entity as Submission;
pub use super::task_queue::Entity as TaskQueue;
pub use super::video::Entity as Video;
pub use super::video_source::Entity as VideoSource;
pub use super::watch_later::Entity as WatchLater;
